name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: name of deployable files
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: output files
        run: ls
      - name: Done
        run: echo 'All done!'
