name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: name of deployable files
        required: true
        type: string
    outputs:
      result:
        description: Output value
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.step-results.outputs.set-result}}
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: output files
        run: ls
      - name: Done
        run: echo 'All done!'
      - name: Set result output
        id: step-results
        run: echo "set-result=success" >> $GITHUB_OUTPUT
